apiVersion: v1
kind: Service
metadata:
  name: karsajobs # service name
  labels:
    app: karsajobs
spec:
  type: NodePort # using node port
  selector:
    app: karsajobs
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30008