apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs # metadata name for this deployment
  labels:
    app: karsajobs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: karsajobs
  template:
    metadata:
      labels:
        app: karsajobs # label for backend
    spec:
      containers:
        - name: karsajobs
          image: ghcr.io/berviantoleo/karsajobs:latest # get image from github package
          ports:
            - containerPort: 8080 # set container port 8080
          env:
            - name: APP_PORT
              value: "8080"
            - name: MONGO_HOST
              value: "mongo"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
